.PHONY: clean All

All:
	@echo "----------Building project:[ leetcode - Debug ]----------"
	@"$(MAKE)" -f  "leetcode.mk"
clean:
	@echo "----------Cleaning project:[ leetcode - Debug ]----------"
	@"$(MAKE)" -f  "leetcode.mk" clean
